name: Deploy

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile Css and Js
        run: |
          npm install
          npm run dev
